package em.network.rpcprotocol;


public enum RequestType {
    LOGIN, LOGOUT, ADD_USER_ACCOUNT, GET_ALL_USERS, MODIFY_USER_ACCOUNT, DELETE_USER_ACCOUNT,
    PRESENT_TO_WORK, LEAVE_WORK, GET_PRESENT_EMPLOYEES, SEND_TASK, GET_TASKS_FOR_EMPLOYEE
}
