package em.network.rpcprotocol;


public enum ResponseType {
    OK, ERROR, LOGGED_IN, LOGGED_OUT, ACCOUNT_ADDED, GOT_ALL_USERS, ACCOUNT_MODIFIED, ACCOUNT_DELETED,
    ADDED_AS_PRESENT, GONE_FROM_WORK, GOT_PRESENT_EMPLOYEES, TASK_SENT, GOT_TASKS_FOR_EMPLOYEE,
    ADDED_AS_PRESENT_UPDATE, GONE_FROM_WORK_UPDATE, TASK_SENT_UPDATE
}
